services:
  postgres:
    image: postgres:16
    container_name: aula-node-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jaime2024
      POSTGRES_DB: loja
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: