services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    environment:
      POSTGRES_USER: mellojr
      POSTGRES_PASSWORD: Jaime2024
      POSTGRES_DB: prova_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: